version: '3.9'

volumes:
  pgdata:

services:

  db:
    image: postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
#    command: gunicorn main:get_app --bind "0.0.0.0:8081" --worker-class aiohttp.GunicornWebWorker
    command: python3 main.py